name       : angband
version    : 4.2.4
release    : 9
source     :
    - https://github.com/angband/angband/archive/4.2.4.tar.gz : 8cf30b0f5c4d096e18a2896b81e5a8fa82215ebdcd3037502673fb70a6c30779
homepage   : https://rephial.org/
license    : GPL-2.0-or-later
component  : games.rpg
summary    : Angband is a free, single-player dungeon exploration game
description: |
    Angband is a graphical dungeon adventure game that uses textual characters to represent the walls and floors of a dungeon and the inhabitants therein, in the vein of games like NetHack and Rogue.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - python-docutils
setup      : |
    # angband uses sysconfdir for its asset installation, so swap that out of etc
    %autogen \
        --bindir=/usr/bin \
        --enable-sdl2 \
        --enable-sdl2_mixer \
        --sysconfdir=/usr/share/
build      : |
    %make
install    : |
    %make_install
