name       : angband
version    : 4.1.3
release    : 3
source     :
    - https://github.com/angband/angband/archive/4.1.3.tar.gz : 9402c4f8da691edbd4567a948c5663e1066bee3fcb4a62fbcf86b5454918406f
license    : GPL-2.0-or-later
component  : games.rpg
summary    : Angband is a free, single-player dungeon exploration game
description: |
    Angband is a free, single-player dungeon exploration game. You play an adventurer seeking riches, fighting monsters, and preparing for a final battle with Morgoth, the Lord of Darkness
builddeps  :
    - python-docutils
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
setup      : |
    %autogen --bindir=/usr/bin \
    --enable-sdl \
    --enable-sdl_mixer
build      : |
    %make
install    : |
    %make_install
