name       : angband
version    : 4.0.5
release    : 1
source     :
    - http://rephial.org/downloads/4.0/angband-4.0.5.tar.gz : 0d769a0f349842b0c78cbcd1804a9e08f064e75ca26b957710e4c2a3eb14f852
license    : GPL-2.0
component  : games.rpg
summary    : Angband is a free, single-player dungeon exploration game
description: |
   Angband is a free, single-player dungeon exploration game. You play an adventurer seeking riches, fighting monsters, and preparing for a final battle with Morgoth, the Lord of Darkness
builddeps  :
    - pkgconfig(ncursesw)
    - python-docutils
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
setup      : |
    %autogen
    %configure \
    --bindir=/usr/bin \
    --enable-sdl \
    --enable-sdl_mixer
build      : |
    %make
install    : |
    %make_install
