name       : angband
version    : 4.2.0
release    : 4
source     :
    - https://github.com/angband/angband/archive/4.2.0.tar.gz : d3e1495c7cc2a4ee66de7b4e612d3b133048072e37504bd2e58a2351ab0fb56d
license    : GPL-2.0-or-later
component  : games.rpg
summary    : Angband is a free, single-player dungeon exploration game
description: |
    Angband is a free, single-player dungeon exploration game. You play an adventurer seeking riches, fighting monsters, and preparing for a final battle with Morgoth, the Lord of Darkness
builddeps  :
    - python-docutils
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
setup      : |
    %autogen --bindir=/usr/bin \
    --enable-sdl2 \
    --enable-sdl2_mixer
build      : |
    %make
install    : |
    %make_install
