name       : angband
version    : 4.2.3
release    : 8
source     :
    - https://github.com/angband/angband/archive/4.2.3.tar.gz : f001299283fb8a81865e07983d54cf04cd0f9addfeb7daeef75ed60f6ca417ff
homepage   : https://rephial.org/
license    : GPL-2.0-or-later
component  : games.rpg
summary    : Angband is a free, single-player dungeon exploration game
description: |
    Angband is a free, single-player dungeon exploration game. You play an adventurer seeking riches, fighting monsters, and preparing for a final battle with Morgoth, the Lord of Darkness
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - python-docutils
setup      : |
    # angband uses sysconfdir for its asset installation, so swap that out of etc
    %autogen \
        --bindir=/usr/bin \
        --enable-sdl2 \
        --enable-sdl2_mixer \
        --sysconfdir=/usr/share/
build      : |
    %make
install    : |
    %make_install
