name       : angband
version    : 4.2.1
release    : 6
source     :
    - https://github.com/angband/angband/archive/4.2.1.tar.gz : acd735c9d46bf86ee14337c71c56f743ad13ec2a95d62e7115604621e7560d0f
license    : GPL-2.0-or-later
component  : games.rpg
summary    : Angband is a free, single-player dungeon exploration game
description: |
    Angband is a free, single-player dungeon exploration game. You play an adventurer seeking riches, fighting monsters, and preparing for a final battle with Morgoth, the Lord of Darkness
builddeps  :
    - python-docutils
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
setup      : |
    # angband uses sysconfdir for its asset installation, so swap that out of etc
    %autogen --bindir=/usr/bin --sysconfdir=/usr/share/ \
    --enable-sdl2 \
    --enable-sdl2_mixer
build      : |
    %make
install    : |
    %make_install
